# Third Place Report(Design, Data, AI) [V2022]
### 2022 Version for Contribution to Architectural Institute of Korea
### 제3 공간 분석과 적용 (디자인, 데이터, 인공지능), 대한건축학회 프로젝트 리포트 기고 버전

##### [DaumBrunch Full Version](https://brunch.co.kr/@njnamju/148)

-----
* Inital research, [MIT Media Lab, City Science](https://www.media.mit.edu/groups/city-science/overview/) <br>
  [Third Place Mobility Energy Consumption Per Person](http://www.njstudio.co.kr/main/project/2016_MobilityEnergyConsumptionMITMediaLab/index.html) <br>

* Paper <br>
  [Lee, N. (2021). Understanding and Analyzing the Characteristics of the Third Place in Urban Design: A Methodology for Discrete and Continuous Data in Environmental Design. In: Yuan, P.F., Yao, J., Yan, C., Wang, X., Leach, N. (eds) Proceedings of the 2020 DigitalFUTURES. CDRF 2020. Springer, Singapore](https://doi.org/10.1007/978-981-33-4400-6_11)  <br>
  

* Contribution <br> [대한건축학회 : Architectural Institute of Korea](https://www.aik.or.kr/)
  제3 공간 분석과 적용 (디자인, 데이터, 인공지능)  <br> https://brunch.co.kr/@njnamju/148 <br>


-----
#### Author: NJ Namju Lee / nj.namju@gmail.com  
###### * Linkedin - https://www.linkedin.com/in/nj-namju-lee-926b3252/    * Git - https://github.com/NamjuLee  

###### * Web - http://www.njstudio.co.kr                                  * Lab - http://www.njslab.com/NJSLabCore/  

###### * Video(English) - https://www.youtube.com/c/njnamjulee            * Writing(English) - https://medium.com/@nj-namju  

###### * Video(Korean) - https://www.youtube.com/c/CodeforDesign          * Writing(Korean) - https://brunch.co.kr/@njnamju  
-----

# 4. Training Models

In [1]:
import pandas as pd
import numpy as np

### 4.1 Import data and process data for fitting models

In [2]:
dfDis = pd.read_csv('data/processed/google-third-place-Boston_DistanceClosest.csv')
dfDis = dfDis.iloc[:, 1:]

dataSetDis = dfDis.to_numpy()
np.random.seed(222)
np.random.shuffle(dataSetDis)
X_dis = dataSetDis[:,:-1]
y_dis = dataSetDis[:,-1:].flatten()

dfDecay = pd.read_csv('data/processed/google-third-place-Boston_DecayClosest.csv')
dfDecay = dfDecay.iloc[:, 1:]
print(dfDecay.shape)

dataSetDecay = dfDecay.to_numpy()
np.random.seed(222)
np.random.shuffle(dataSetDecay)
X_decay = dataSetDecay[:,:-1]
y_decay = dataSetDecay[:,-1:].flatten()

(4273, 96)


In [3]:
# https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

XTrain_dis, XTest_dis, yTrain_dis, yTest_dis =train_test_split(X_dis, y_dis, test_size=0.2)
std_scale = StandardScaler()
std_scale.fit(XTrain_dis)
XTrainStd_dis = std_scale.transform(XTrain_dis)
XTestStd_dis  = std_scale.transform(XTest_dis)

XTrain_decay, XTest_decay, yTrain_decay, yTest_decay =train_test_split(X_decay, y_decay, test_size=0.2)
std_scale = StandardScaler()
std_scale.fit(XTrain_decay)
XTrainStd_decay = std_scale.transform(XTrain_decay)
XTestStd_decay  = std_scale.transform(XTest_decay)

### 4.2 Logistic Regression

In [4]:
from sklearn.linear_model import LogisticRegression

lrL2_dis =  LogisticRegression(multi_class='multinomial', solver='lbfgs', penalty='none', random_state=2)
lrL2_dis.fit(XTrainStd_dis, yTrain_dis)

print('shape: ', lrL2_dis.coef_.shape)
print('coef:', lrL2_dis.coef_)
print('intercept:', lrL2_dis.intercept_)

shape:  (91, 95)
coef: [[-3.80878434  2.10879781 -0.09920027 ... -0.63685661  0.26779251
   0.19140878]
 [ 1.9473164  -5.59547751  0.0766282  ...  0.27132716 -0.35410094
  -0.59983327]
 [ 0.20871056  0.19473616 -0.57842961 ...  0.15094114  0.09438069
   0.25179084]
 ...
 [-0.76805817 -0.47794594 -0.16629085 ... -6.29332175 -1.15386821
   1.69646368]
 [-0.11460645 -0.39936744 -0.0127533  ... -0.10222725 -5.12509915
   0.16440904]
 [ 0.42681349 -0.88215166 -0.17873336 ...  0.68382575  0.78317262
  -3.51671529]]
intercept: [-1.99138982  0.24490494 -4.89468697 -4.57840931 -4.89508435  4.76577684
  3.25014537  5.04223445  1.87641311 -4.89489743 -1.90450475  1.96766232
 -4.89483695 -4.89537603  5.35989589  1.41864382 -0.19365097 -4.89523889
 -4.89484305 -2.39703807  2.38176691  5.24327343 -4.89495089 -4.89498455
  6.21965826  5.67139578  4.14189974 -4.89489739 -0.87685677 -0.10044901
  4.86701338 -4.02822612  4.57790741 -0.36979121  0.10972515  1.28165903
  5.7965909   0.00939465  3.30432065

c:\Users\namju\miniconda3\envs\tf-gpu-2022\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [5]:
lrL2_decay =  LogisticRegression(multi_class='multinomial', solver='lbfgs', penalty='none', random_state=2)
lrL2_decay.fit(XTrainStd_decay, yTrain_decay)

print('shape: ', lrL2_decay.coef_.shape)
print('coef:', lrL2_decay.coef_)
print('intercept:', lrL2_decay.intercept_)

shape:  (93, 95)
coef: [[ 6.43848288e+00 -1.65287253e-01  2.83351597e-03 ...  1.17761368e-01
   2.36220075e-03 -5.81784731e-02]
 [-5.25078992e-01  9.25610590e+00  9.70041526e-03 ...  1.00158674e-01
  -2.01049984e-02 -2.53652438e-01]
 [-1.29200767e-02  4.38508332e-02  2.27013890e-01 ...  5.79630864e-02
  -1.28720814e-02  7.45446025e-03]
 ...
 [ 6.77099821e-01  1.46043901e-01 -1.73646739e-02 ...  1.28368559e+01
  -3.48459897e-02 -3.71908031e-01]
 [-1.76336857e-01 -6.26714985e-02  5.10548620e-02 ... -1.72153776e-01
   6.95433549e+00 -8.20225346e-02]
 [-1.18107576e-01 -8.33749111e-02 -5.12475420e-02 ... -9.32418676e-02
  -7.95171323e-02  5.27075894e+00]]
intercept: [-1.47489405e+00 -3.02796258e-01 -1.94145647e+00 -1.92932303e+00
 -1.94141989e+00  3.55019056e+00  1.85421849e+00  3.52070407e+00
  1.10570027e+00 -1.94149886e+00 -1.03648056e+00  3.00127855e-01
 -1.94142120e+00 -1.94146130e+00  5.32090677e+00 -8.86167269e-01
 -1.04135720e+00 -1.94144795e+00 -1.94144958e+00 -1.32433450e+00
 -3.2

c:\Users\namju\miniconda3\envs\tf-gpu-2022\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [6]:
# https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html

from sklearn.metrics import precision_score
from sklearn.metrics import confusion_matrix

pred_logistic_dis = lrL2_dis.predict(XTestStd_dis)
print(pred_logistic_dis)
print(precision_score(yTest_dis, pred_logistic_dis,  average='micro'))

[27.  5. 50. 25. 69. 77. 56. 26. 80. 31. 22. 50. 86. 80. 31. 50. 22. 14.
 37. 76. 83. 69. 86. 83. 77. 85. 50. 40. 37. 29. 69. 46. 55.  7. 77. 46.
 68. 82. 44. 55. 25. 85. 21. 37. 40.  6. 59. 44. 69. 53. 37. 31. 67. 53.
 16. 86. 86. 59. 59. 25.  7. 49. 58. 16. 29. 37. 26. 59. 69. 69. 85. 27.
 46. 16. 16. 25. 25. 37. 50.  7. 14. 29. 36. 25. 16. 33. 82. 59.  7. 22.
 86. 69. 25. 29. 92. 86.  6. 29. 64. 25. 56.  7. 27. 22. 69. 59. 80. 59.
 31. 69. 68. 59. 16. 33. 25. 14. 86.  5. 69. 69. 31. 55. 73. 40. 86. 64.
  7. 27. 82. 37. 36. 92.  1. 29. 46. 55. 86. 69. 91. 64. 46. 14.  7. 37.
 59. 76. 56. 58. 56.  6. 29. 68. 31. 77. 21. 80. 69. 73. 68. 31. 33. 69.
 82. 86. 92. 69. 26. 49.  7. 22. 77. 82. 49. 69. 56. 69. 83. 14. 85. 49.
 50. 44. 37. 80. 59. 64. 44. 59. 50. 26. 25. 77. 76.  5. 59. 82. 37. 37.
 53. 29. 16. 59. 49. 16. 80. 92. 85. 80. 50. 14. 33. 49. 86. 82. 59. 83.
 59.  7. 22. 77. 69. 59. 69. 69. 92. 56. 31. 83. 33. 69. 74. 40.  7. 49.
 59. 69. 80. 52. 77. 69. 46. 25. 25. 29. 50. 25. 29

In [7]:
pred_logistic_decay = lrL2_decay.predict(XTestStd_decay)
print(pred_logistic_decay)
print(precision_score(yTest_decay, pred_logistic_decay,  average='micro'))

[14. 60. 80. 34.  7. 49. 14. 69. 26. 31. 86. 29. 33. 43. 92. 37. 29. 33.
 92. 33. 53. 27.  1. 60. 14. 22. 40. 55. 25. 82. 26. 64. 91. 50. 34. 25.
 80. 61. 94. 60. 92. 30. 37. 22. 86. 16. 44. 83. 80. 87. 14. 46. 27. 31.
 22. 80. 69. 69. 29. 25. 31. 25. 54. 73. 25. 61. 78. 80. 76. 26.  7. 43.
 56. 49. 31. 52. 80. 52. 44. 76. 77. 25.  5. 59. 16. 25. 31. 44. 60. 80.
 82. 64. 92. 76. 27. 46. 55. 64. 40. 26. 16. 68. 82. 46. 80. 31. 69. 69.
 58.  7. 11. 46.  8.  5. 25. 92. 22. 76. 86. 25. 86. 22. 53. 58. 26. 73.
 60. 49. 92. 92. 86. 14. 58.  5. 49. 50. 21. 27. 83. 30. 77. 46. 73. 94.
  7. 69. 73. 52. 37. 60.  5. 43. 35. 46. 52. 77. 60. 43. 27. 46. 44. 80.
 14. 44. 49. 50.  7. 16. 77. 21. 73. 76. 27. 73. 83. 37. 82. 50. 92. 92.
 22.  1. 80. 33.  7. 31. 14. 56. 26. 50. 37. 27. 86. 31. 59. 85. 86. 46.
 49. 44. 83. 85. 92.  8. 37. 26. 26. 46. 73. 16.  5. 46. 50. 29. 37.  5.
 86. 52. 86. 68. 59. 35. 56. 73. 20. 80.  5. 31. 59. 69. 14. 92. 16. 34.
 49. 27. 26. 69. 44. 86.  8. 46. 44. 59. 49. 69. 69

In [8]:
print(lrL2_dis.predict_proba(XTestStd_dis))
print(confusion_matrix(yTest_dis, pred_logistic_dis))

[[5.79654095e-08 4.74558711e-03 1.76808208e-09 ... 9.37451763e-02
  1.93145602e-04 1.06479056e-06]
 [1.12182040e-06 2.33785302e-07 1.62814580e-09 ... 1.65607980e-01
  1.08421736e-08 2.24323269e-08]
 [1.55231200e-05 2.08336820e-09 9.00719432e-11 ... 7.53577133e-10
  9.72986369e-05 4.82602571e-11]
 ...
 [5.68902341e-08 5.45116969e-03 1.82387681e-09 ... 8.28208197e-02
  1.93909865e-04 1.16722610e-06]
 [1.10735132e-06 2.53043344e-12 2.96845771e-11 ... 2.30386372e-10
  3.98708693e-22 6.35256831e-09]
 [8.12586459e-06 1.15432943e-08 3.71677504e-09 ... 3.90177872e-09
  1.34861322e-03 1.17774547e-08]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 8 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [9]:
print(lrL2_decay.predict_proba(XTestStd_decay))
print(confusion_matrix(yTest_decay, pred_logistic_decay))

[[2.16359753e-23 1.86140179e-24 1.76558933e-22 ... 3.18391857e-24
  1.06840553e-23 3.45757717e-23]
 [7.04623746e-26 4.13779511e-19 4.88984933e-24 ... 3.61710326e-25
  9.91549333e-27 1.12691078e-25]
 [6.21003320e-23 2.76711994e-21 4.36846674e-25 ... 1.80220207e-20
  5.47754683e-23 3.20506341e-22]
 ...
 [1.35324309e-22 2.61964835e-20 1.56643979e-24 ... 1.39552506e-21
  1.00638628e-21 1.90277723e-23]
 [1.04708169e-24 1.71812524e-24 5.67885520e-25 ... 2.57843680e-28
  2.06149254e-24 4.06068010e-25]
 [4.19539847e-17 8.80513255e-22 5.78932629e-21 ... 2.35181785e-24
  2.01746710e-19 6.50256724e-21]]
[[ 3  0  0 ...  0  0  0]
 [ 0  1  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ... 11  0  0]
 [ 0  0  0 ...  0  1  0]
 [ 0  0  1 ...  0  0  0]]


In [10]:
prob = lrL2_decay.predict_proba(XTestStd_decay)[0]
prob

array([2.16359753e-23, 1.86140179e-24, 1.76558933e-22, 2.10122778e-22,
       1.76410297e-22, 1.62433429e-21, 1.67946154e-19, 2.28544999e-21,
       2.57421691e-24, 1.76731397e-22, 4.32469121e-22, 5.70836917e-21,
       1.76415629e-22, 1.76578589e-22, 8.47080786e-01, 4.41534621e-24,
       1.35648470e-17, 1.76524334e-22, 1.76530943e-22, 9.76191965e-21,
       1.34767060e-20, 1.27715075e-20, 1.76518877e-22, 1.76566520e-22,
       1.52919185e-01, 4.49890680e-20, 5.87452524e-17, 1.76500088e-22,
       8.83926864e-20, 4.49929733e-23, 6.58917842e-19, 5.00206783e-23,
       5.06262707e-18, 2.14683467e-21, 3.45184120e-21, 5.83841444e-25,
       3.00018808e-19, 8.94540214e-23, 3.07955379e-21, 1.76879176e-22,
       1.76565492e-22, 2.11637771e-24, 3.16611165e-18, 1.76479767e-22,
       2.58163031e-25, 3.13793281e-22, 1.76526264e-22, 1.38767660e-23,
       1.73611730e-22, 1.71094635e-23, 2.43642855e-08, 2.21425427e-16,
       6.10328240e-23, 6.36229351e-17, 4.26660106e-09, 4.54352952e-22,
      

### 4.3. SVM

In [11]:
# https://scikit-learn.org/stable/modules/generated/sklearn.svm.SVC.html
from sklearn import svm 

lrSVM_dis = svm.SVC(kernel='linear', random_state=2)
lrSVM_dis.fit(XTrainStd_dis, yTrain_dis)

lrSVM_decay = svm.SVC(kernel='linear', random_state=2)
lrSVM_decay.fit(XTrainStd_decay, yTrain_decay)

SVC(kernel='linear', random_state=2)

In [12]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

predSVM_dis = lrSVM_dis.predict(XTestStd_dis)
print(predSVM_dis)
print(accuracy_score(yTest_dis, predSVM_dis))

[92. 92. 86. 82. 92. 86. 26. 26. 43. 86. 73. 50. 86. 80. 86. 86. 25. 86.
 37. 76. 77. 69. 37. 86. 77. 46. 50. 25. 37. 29. 69. 92. 55. 77. 69. 29.
 68. 86. 86. 55. 59. 16. 21. 37. 25. 31. 59. 86. 69. 22. 37. 86. 59. 59.
 16. 86. 43. 77. 59. 86. 26. 49. 58. 16. 49. 68. 82. 69. 69. 69. 46. 92.
 49. 16. 16. 25. 25. 37. 50. 86. 46. 29. 36. 82. 16. 33. 37. 59. 59. 22.
 86. 68. 86. 29. 92. 86. 29. 29. 64. 25. 85. 35. 27. 91. 64. 16. 21. 59.
 31. 69. 68. 29. 16. 86. 59. 82. 37. 59. 69. 92. 31. 64. 73. 59. 86. 59.
 59. 27. 86. 59. 36. 92. 26. 29. 22. 55. 86. 69. 37. 86. 22. 61. 86. 59.
 59. 76. 26. 58. 69. 14. 29. 68. 31. 86. 21. 22. 49.  6. 69. 31. 82. 68.
 82.  6. 33. 68. 76. 49. 82. 22. 82. 86. 49. 54. 56. 69. 83. 82. 86. 49.
 86.  5. 37. 26. 59. 64. 44. 16. 86. 86. 59. 59. 76.  5. 59. 82. 59. 37.
 59. 29. 16. 59. 49. 16. 49. 29. 85. 80. 50.  6. 82. 49. 77. 37. 59. 86.
 25. 76. 59.  7. 69. 59. 29. 59. 92. 86. 86. 86. 55. 69. 92.  7. 59. 49.
 59. 92. 22. 59. 59. 68. 29. 16. 25. 29. 25. 25. 49

In [13]:
predSVM_decay = lrSVM_decay.predict(XTestStd_decay)
print(predSVM_decay)
print(accuracy_score(yTest_decay, predSVM_decay))

[14. 26. 80. 34.  7. 69. 14. 69. 26. 68. 86. 29. 33. 43. 92. 85. 29. 27.
 92. 27. 53. 27.  1. 27. 29. 22. 26. 55. 25. 82. 26. 64. 91. 50. 82. 25.
 80. 61. 94. 60. 92. 30. 16. 22. 86. 16. 17. 32. 80. 87. 14. 46. 27. 31.
 43. 68. 68.  5. 29. 25.  5. 86. 83. 73. 25. 54. 78. 80. 76. 54. 29. 43.
 56. 49. 31. 14. 80. 85. 44. 76. 77. 14.  7. 59. 16. 25. 31. 44. 60. 80.
 37. 86. 92. 76. 60. 21. 55. 64. 26. 61. 86. 68. 91. 29. 80. 62. 33. 69.
 58. 82. 11. 46.  8.  5. 14. 92. 22. 76. 31. 56. 44. 11. 53. 43. 54. 25.
 49. 49. 92. 92. 31. 14. 43. 68. 49. 50. 21. 27. 76. 30. 91. 46. 86. 46.
  7. 69. 73. 52. 37. 49.  5. 73. 35. 29. 68. 77. 26. 43. 27. 46. 27. 80.
  7. 26. 49.  8.  7. 16. 77. 21. 73. 76. 27. 73. 14. 37. 37. 50. 92. 92.
 22. 16. 80. 33.  7. 31. 14. 22. 26. 11. 25. 27. 86. 31. 50. 83. 11. 27.
 49. 44. 83. 88. 92.  8. 37. 21. 74. 46. 73. 16.  5. 46. 11. 29. 77. 86.
 86. 14. 82. 68. 59. 50. 33. 73. 83. 80.  5.  5. 59. 87. 59. 92. 16.  7.
 49. 27. 26. 69.  5. 37.  8. 46. 44. 59. 49. 69. 69

In [14]:
print(confusion_matrix(yTest_dis, predSVM_dis))

[[ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  1  0  0]
 [ 0  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ... 12  0  0]
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0  0  0]]


-----
### References & Useful links

Lee, N. (2021). Understanding and Analyzing the Characteristics of the Third Place in Urban Design: A Methodology for Discrete and Continuous Data in Environmental Design. In: Yuan, P.F., Yao, J., Yan, C., Wang, X., Leach, N. (eds) Proceedings of the 2020 DigitalFUTURES. CDRF 2020. Springer, Singapore. https://doi.org/10.1007/978-981-33-4400-6_11



Oldenburg, R., Brissett, (1982). D.: The third place. Qual. Sociol. 5(4), 265–284



Lee, Namju. (2022). Computational Design, Seoul, Bookk, https://brunch.co.kr/@njnamju/144



Lee, Namju, (2022). Discrete Urban Space and Connectivity, https://nj-namju.medium.com/discrete-urban-space-and-connectivity-492b3dbd0a81



Woo. Junghyun, (2022). Numeric Network Analysis for Pedestrians, https://axuplatform.medium.com/0-numeric-network-analysis-47a2538e636c



Lee, Namju, (2022). Computational Design Thinking for Designers, https://nj-namju.medium.com/computational-design-thinking-for-designers-68224bb07f5c



Lee, Namju. (2016). Third Place Mobility Energy Consumption Per Person, http://www.njstudio.co.kr/main/project/2016_MobilityEnergyConsumptionMITMediaLab 
