# **Data in Design, AI for Urban Data and Visualization**

#### Data, Design Computation, Artificial Intelligence, Visualization, Harvard GSD J Term 2023


**KEYWORD:**
Vector, Raster, Urban Data, GIS, Data Processing, Data Science, Design Science, Data Mining, Machine Learning, Artificial Intelligence, Visualization, Mapping, Design Decision-Making

-----

#### Instructor : NJ Namju Lee / nj.namju@gmail.com  
###### * Linkedin - https://www.linkedin.com/in/nj-namju-lee-926b3252/    * Git - https://github.com/NamjuLee  

###### * Web - https://namjulee.github.io/njs-lab-public/

###### * Video(English) - https://www.youtube.com/c/njnamjulee            * Writing(English) - https://medium.com/@nj-namju  

###### * Video(Korean) - https://www.youtube.com/c/CodeforDesign          * Writing(Korean) - https://brunch.co.kr/@njnamju  
-----

PART 02 Programming Data Processing

# LAB 03 Numpy basic

NumPy is a Python library.

NumPy is used for working with arrays.

NumPy is short for "Numerical Python"

---

In [1]:
import numpy as np
np.__version__

'1.21.5'

### Numpy Array


In [2]:
# arange

myArray = np.arange(0, 10, 2)
print(myArray.shape)
print(myArray)

(5,)
[0 2 4 6 8]


In [3]:
# https://www.geeksforgeeks.org/numpy-linspace-python/

myArray = np.linspace(0, 10, 5)
print(myArray.shape)
print(myArray)

(5,)
[ 0.   2.5  5.   7.5 10. ]


In [4]:
# array

array_1D = np.array([1,2,3,4,5])
print(array_1D)
print(type(array_1D))
print(array_1D.shape)
print(array_1D[3])

array_1D[1] = 9
print(array_1D)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
4
[1 9 3 4 5]


In [5]:
array_2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(array_2D)
print(type(array_2D))
print(array_2D.shape)
print(array_2D[1,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
(3, 3)
6


In [6]:
a3 = np.array([
    [[1, 2, 3],  [4, 5, 6],  [7, 8, 9]],
    [[11,21,31], [14,15,16], [17,18,19]],
    [[21,22,23], [24,25,26], [27,28,29]]
    ])

print(a3)
print(type(a3))
print(a3.shape)
print(a3[1,2,2])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 21 31]
  [14 15 16]
  [17 18 19]]

 [[21 22 23]
  [24 25 26]
  [27 28 29]]]
<class 'numpy.ndarray'>
(3, 3, 3)
19


In [7]:
# zeros

myArray = np.zeros(9)
print(myArray.shape)
print(myArray)

(9,)
[0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
myArray = np.zeros((3,3))
print(myArray.shape)
print(myArray)

myArray = np.zeros((3,3), dtype=int)
print(myArray.shape)
print(myArray)

myArray = np.zeros((3,3), dtype=bool)
print(myArray.shape)
print(myArray)

(3, 3)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
(3, 3)
[[0 0 0]
 [0 0 0]
 [0 0 0]]
(3, 3)
[[False False False]
 [False False False]
 [False False False]]


In [9]:
# ones

myArray = np.ones(9)
print(myArray.shape)
print(myArray)

(9,)
[1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [10]:
myArray = np.ones((3,3))
print(myArray.shape)
print(myArray)

myArray = np.ones((3,3), dtype=bool)
print(myArray.shape)
print(myArray)

(3, 3)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
(3, 3)
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [11]:
# full

myArray = np.full((3,3), 0.5)
print(myArray.shape)
print(myArray)

myArray = np.full((3,3), 2, dtype=float)
print(myArray.shape)
print(myArray)

myArray = np.full((3,3), 2, dtype=int)
print(myArray.shape)
print(myArray)

(3, 3)
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]]
(3, 3)
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
(3, 3)
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [12]:
# empty

myArray = np.empty((3,3))
print(myArray.shape)
print(myArray)

(3, 3)
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [13]:
# eye

myArray = np.eye(3) # identity matrix
print(myArray.shape)
print(myArray)

(3, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
# tri

myArray = np.tri(3) # identity matrix
print(myArray.shape)
print(myArray)

myArray = np.tri(3, dtype=bool)
print(myArray.shape)
print(myArray)


(3, 3)
[[1. 0. 0.]
 [1. 1. 0.]
 [1. 1. 1.]]
(3, 3)
[[ True False False]
 [ True  True False]
 [ True  True  True]]


In [15]:
# random

myArray = np.random.random()
# print(myArray.shape)
print(type(myArray))
print(myArray)

<class 'float'>
0.7562625585944072


In [16]:
myArray = np.random.random((3,3)) # normalized values
print(myArray.shape)
print(myArray)

(3, 3)
[[0.79007841 0.10456217 0.38178381]
 [0.3721314  0.12758711 0.77392289]
 [0.4029512  0.0510637  0.29884925]]


In [17]:
# randint

myArray = np.random.randint(0, 10, (3,3))
print(myArray.shape)
print(myArray)

(3, 3)
[[4 3 8]
 [2 5 3]
 [0 0 0]]


In [18]:
# normal distribution
# https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html

myArray = np.random.normal(0, 1, (3,3)) 
print(myArray.shape)
print(myArray)

(3, 3)
[[-0.49968165 -0.21054085  0.63132976]
 [ 0.62812244  0.70835096 -0.87146539]
 [ 0.37514389 -2.52987718 -0.194508  ]]


In [19]:
# uniform distribution

myArray = np.random.rand(3,3) 
print(myArray.shape)
print(myArray)

(3, 3)
[[0.53923826 0.08166785 0.75850785]
 [0.79692739 0.57954408 0.28836829]
 [0.60096515 0.59478233 0.061522  ]]


In [20]:
# standard normal distribution

myArray = np.random.randn(3,3) 
print(myArray.shape)
print(myArray)

(3, 3)
[[ 0.27457041  0.45273988  0.77013393]
 [ 1.15699545  1.03896698  0.02792977]
 [-0.80556493  0.88246782  0.19295575]]


In [21]:
myArray = np.random.randint(0, 10, (3,3))
print(myArray)
print('dtype: ', myArray.dtype )
print('ndim: ', myArray.ndim )
print('shape: ', myArray.shape )
print('size: ', myArray.size )
print('itemsize(Byte): ', myArray.itemsize )
print('nbytes(Byte): ', myArray.nbytes )
print('strides(Byte): ', myArray.strides )

[[4 0 0]
 [2 5 0]
 [6 4 6]]
dtype:  int32
ndim:  2
shape:  (3, 3)
size:  9
itemsize(Byte):  4
nbytes(Byte):  36
strides(Byte):  (12, 4)


In [22]:
# date

myDate = np.array('2023-01-01', dtype=np.datetime64)
print(type(myDate))
print(myDate)

<class 'numpy.ndarray'>
2023-01-01


In [23]:
myDateArray = myDate + np.arange(12)
print(type(myDateArray))
print(myDateArray)

<class 'numpy.ndarray'>
['2023-01-01' '2023-01-02' '2023-01-03' '2023-01-04' '2023-01-05'
 '2023-01-06' '2023-01-07' '2023-01-08' '2023-01-09' '2023-01-10'
 '2023-01-11' '2023-01-12']


---
### Indexing Array 

In [24]:
myArray = np.arange(0, 9, 1)
print(myArray)
print(myArray[0])
print(myArray[1])
print(myArray[-1])
print(myArray[-2])

[0 1 2 3 4 5 6 7 8]
0
1
8
7


In [25]:
myArray = np.arange(0, 9, 1).reshape(3,3)

print(myArray)
print(myArray[0, 0])
print(myArray[1, 2])
print(myArray[-3, -2])
print(myArray[-1, -1])
print(myArray[1, 1:3])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
0
5
1
8
[4 5]


In [26]:
myArray = np.arange(0, 3 * 3 * 3, 1).reshape(3,3,3)
print(myArray)
print(myArray[0, 0, 0])
print(myArray[-1, -1, -1])
print(myArray[2, 2, 2])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
0
26
26


---
### Slicing arrays

In [27]:
myArray = np.arange(0, 9, 1)
print(myArray)
print('--------------------------')
print(myArray[0 : 2])
print(myArray[3 : 7])
print(myArray[  : 1])
print(myArray[  : 3])
print(myArray[: : 3])
print(myArray[: : -1])

[0 1 2 3 4 5 6 7 8]
--------------------------
[0 1]
[3 4 5 6]
[0]
[0 1 2]
[0 3 6]
[8 7 6 5 4 3 2 1 0]


In [28]:
conditions = [False, True, False, False, True, False, True, False, False]
print(myArray[conditions])

[1 4 6]


In [29]:
myArray = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(myArray)
print('--------------------------')
print(myArray[:])
print('--------------------------')
print(myArray[2, :])
print('--------------------------')
print(myArray[:2, :2])
print('--------------------------')
print(myArray[1:, ::-1])
print('--------------------------')
print(myArray[::-1, ::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------
[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------
[7 8 9]
--------------------------
[[1 2]
 [4 5]]
--------------------------
[[6 5 4]
 [9 8 7]]
--------------------------
[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [30]:
conditions = np.random.randint(0, 2, (3,3), dtype=bool)
print(conditions)
print(myArray[conditions])

[[False False  True]
 [ True False  True]
 [False False  True]]
[3 4 6 9]


In [31]:
myArray = np.arange(0, 9, 1)
print(myArray)
print('--------------------------')
myArray[4] = 10
myArray[3] = 11
print(myArray)

print('--------------------------')
myArray[:-2] = 0
print(myArray)

print('--------------------------')
i = np.array([0, 1, 2])
myArray[i] = -1
print(myArray)

print('--------------------------')
myArray[ [-1, -2] ] += 2
print(myArray)

[0 1 2 3 4 5 6 7 8]
--------------------------
[ 0  1  2 11 10  5  6  7  8]
--------------------------
[0 0 0 0 0 0 0 7 8]
--------------------------
[-1 -1 -1  0  0  0  0  7  8]
--------------------------
[-1 -1 -1  0  0  0  0  9 10]


In [32]:
array_2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(array_2D)
print('--------------------------')
array_2D[0, 0] = 10
array_2D[1, 1] = 20
array_2D[2, 2] = 30
print(array_2D)
print('--------------------------')
array_2D[1] = 9
print(array_2D)
print('--------------------------')
array_2D[:, 2] = -1
print(array_2D)
print('--------------------------')
row = np.array([0, 1])
col = np.array([1, 2])
array_2D[row, col] = 0
print(array_2D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------
[[10  2  3]
 [ 4 20  6]
 [ 7  8 30]]
--------------------------
[[10  2  3]
 [ 9  9  9]
 [ 7  8 30]]
--------------------------
[[10  2 -1]
 [ 9  9 -1]
 [ 7  8 -1]]
--------------------------
[[10  0 -1]
 [ 9  9  0]
 [ 7  8 -1]]


In [33]:
# insert

myArray1 = np.arange(0, 3, 1)

print(myArray1)
print('--------------------------')
myArray2 = np.insert(myArray1, 0, -1)
print(myArray2)
myArray2 = np.insert(myArray1, 2, 10)
print(myArray2)

[0 1 2]
--------------------------
[-1  0  1  2]
[ 0  1 10  2]


In [34]:
array_2D = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(array_2D)
print('--------------------------')

b2 = np.insert(array_2D, 1, 11, axis=0)
print(b2)

print('--------------------------')
c2 = np.insert(array_2D, -1, 11, axis=1)
print(c2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------
[[ 1  2  3]
 [11 11 11]
 [ 4  5  6]
 [ 7  8  9]]
--------------------------
[[ 1  2 11  3]
 [ 4  5 11  6]
 [ 7  8 11  9]]


In [35]:
# delete

myArray1 = np.arange(0, 9, 1)
print(myArray1)
arrayRemoved = np.delete(myArray1, 1)
print(arrayRemoved)

[0 1 2 3 4 5 6 7 8]
[0 2 3 4 5 6 7 8]


In [36]:
array_2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(array_2D)
print('--------------------------')
barray_2D_Removed = np.delete(array_2D, 1, axis=0)
print(barray_2D_Removed)
print('--------------------------')
barray_2D_Removed = np.delete(array_2D, 2, axis=1)
print(barray_2D_Removed)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------
[[1 2 3]
 [7 8 9]]
--------------------------
[[1 2]
 [4 5]
 [7 8]]


In [37]:
array_2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(array_2D)
print('--------------------------')
print(array_2D[:2, :2])
print('--------------------------')
a2_sub = array_2D[:2, :2]
print(a2_sub)
print('---------------')
a2_sub[:,:] = -10
print(a2_sub)
print(array_2D) # !reference, not deep copy unlike normal list in Python

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------
[[1 2]
 [4 5]]
--------------------------
[[1 2]
 [4 5]]
---------------
[[-10 -10]
 [-10 -10]]
[[-10 -10   3]
 [-10 -10   6]
 [  7   8   9]]


In [38]:
array_2D = np.array([[1,2,3], [4,5,6], [7,8,9]])

print(array_2D)
print('--------------------------')
array_2D_copy = array_2D[:2, :2].copy()
print(array_2D_copy)
print('--------------------------')
array_2D_copy[:, :] = -1
print(array_2D_copy)
print(array_2D)



[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------------
[[1 2]
 [4 5]]
--------------------------
[[-1 -1]
 [-1 -1]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [39]:
# transpose
# https://numpy.org/doc/stable/reference/generated/numpy.transpose.html

array_2D = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(array_2D)
print(array_2D.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [40]:
# reshape

array = np.arange(9)
print(array)
print(array.reshape(3,3))

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [41]:
array = np.arange(7)
print(array)

print('--------------------------')
array.resize((2, 2))
print(array)

array = np.arange(7)
print('--------------------------')
array.resize((5, 2))
print(array)

array = np.arange(7)
print('--------------------------')
array.resize((3, 3, 3))
print(array)

[0 1 2 3 4 5 6]
--------------------------
[[0 1]
 [2 3]]
--------------------------
[[0 1]
 [2 3]
 [4 5]
 [6 0]
 [0 0]]
--------------------------
[[[0 1 2]
  [3 4 5]
  [6 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]


In [42]:
array_a = np.arange(0, 9).reshape(3,3)
print(array_a)

array_b = np.arange(10, 19).reshape(3,3)
print(array_b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [43]:
print(np.append(array_a, array_b))
print('--------------------------')
print(np.append(array_a, array_b, axis=0))
print('--------------------------')
print(np.append(array_a, array_b, axis=1))


[ 0  1  2  3  4  5  6  7  8 10 11 12 13 14 15 16 17 18]
--------------------------
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
--------------------------
[[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]
 [ 6  7  8 16 17 18]]


In [44]:
print(np.concatenate([array_a, array_b]))
print('--------------------------')
print(np.concatenate([array_a, array_b], axis=1))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
--------------------------
[[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]
 [ 6  7  8 16 17 18]]


In [45]:
print(np.vstack([array_a, array_b]))
print('--------------------------')
print(np.hstack([array_a, array_b]))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
--------------------------
[[ 0  1  2 10 11 12]
 [ 3  4  5 13 14 15]
 [ 6  7  8 16 17 18]]


In [46]:
# split()
array = np.arange(10, 20)
print(array)
print('--------------------------')
print(np.split(array, [7]))
print(np.split(array, [2, 4, 8]))

[10 11 12 13 14 15 16 17 18 19]
--------------------------
[array([10, 11, 12, 13, 14, 15, 16]), array([17, 18, 19])]
[array([10, 11]), array([12, 13]), array([14, 15, 16, 17]), array([18, 19])]


In [47]:
# vsplit

array = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(array)
print('--------------------------')
a, b = np.vsplit(array, [2])
print(a)
print('--------------------------')
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------------------
[[0 1 2]
 [3 4 5]]
--------------------------
[[6 7 8]]


In [48]:
# hsplit

array = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(array)
print('--------------------------')
a, b = np.hsplit(array, [2])
print(a)
print('--------------------------')
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------------------
[[0 1]
 [3 4]
 [6 7]]
--------------------------
[[2]
 [5]
 [8]]


---

### Arithmetic Operators

In [49]:
array = np.arange(0, 10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


In [50]:
print(array + 1)
print(np.add(array, 10))

[ 1  2  3  4  5  6  7  8  9 10]
[10 11 12 13 14 15 16 17 18 19]


In [51]:
print(array - 10)
print(np.subtract(array, 10))

[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1]
[-10  -9  -8  -7  -6  -5  -4  -3  -2  -1]


In [52]:
print(array * 2)
print(np.multiply(array, 2))

[ 0  2  4  6  8 10 12 14 16 18]
[ 0  2  4  6  8 10 12 14 16 18]


In [53]:
print(array / 2)
print(np.divide(array, 2))

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [54]:
print(array // 2)
print(np.floor_divide(array, 2))

[0 0 1 1 2 2 3 3 4 4]
[0 0 1 1 2 2 3 3 4 4]


In [55]:
print(array % 2)
print(np.mod(array, 2))

[0 1 0 1 0 1 0 1 0 1]
[0 1 0 1 0 1 0 1 0 1]


In [56]:
print(array ** 2)
print(np.power(array, 2))

[ 0  1  4  9 16 25 36 49 64 81]
[ 0  1  4  9 16 25 36 49 64 81]


In [57]:
print(array * -1)
print(-array)
print(np.negative(array))

[ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]
[ 0 -1 -2 -3 -4 -5 -6 -7 -8 -9]


In [58]:
array1 = np.arange(0, 10)
print(array1)
array2 = np.full((10), 2)
print(array2)

[0 1 2 3 4 5 6 7 8 9]
[2 2 2 2 2 2 2 2 2 2]


In [59]:
print(array1 + array2)
print(np.add(array1, array2))
print('--------------------------')
print(array1 - array2)
print(np.subtract(array1, array2))

[ 2  3  4  5  6  7  8  9 10 11]
[ 2  3  4  5  6  7  8  9 10 11]
--------------------------
[-2 -1  0  1  2  3  4  5  6  7]
[-2 -1  0  1  2  3  4  5  6  7]


In [60]:
print(array1 * array2)
print(np.multiply(array1, array2))
print('--------------------------')
print(array1 / array2)
print(np.divide(array1, array2))

[ 0  2  4  6  8 10 12 14 16 18]
[ 0  2  4  6  8 10 12 14 16 18]
--------------------------
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]


In [61]:
array1 = np.arange(0, 16).reshape(4,4)
print(array1)
print('--------------------------')
array2 = np.random.randint(0, 16, size=(4,4))
print(array2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
--------------------------
[[12  3  5  7]
 [14  8  0  8]
 [ 8  8  3 14]
 [14  7 12 12]]


In [62]:
print(array1 + array2)
print('--------------------------')
print(array1 - array2)

[[12  4  7 10]
 [18 13  6 15]
 [16 17 13 25]
 [26 20 26 27]]
--------------------------
[[-12  -2  -3  -4]
 [-10  -3   6  -1]
 [  0   1   7  -3]
 [ -2   6   2   3]]


In [63]:
print(array1 * array2)
print('--------------------------')
print(array1 / array2)

[[  0   3  10  21]
 [ 56  40   0  56]
 [ 64  72  30 154]
 [168  91 168 180]]
--------------------------
[[0.         0.33333333 0.4        0.42857143]
 [0.28571429 0.625             inf 0.875     ]
 [1.         1.125      3.33333333 0.78571429]
 [0.85714286 1.85714286 1.16666667 1.25      ]]


C:\Users\namju\AppData\Local\Temp\ipykernel_9876\984843346.py:3: RuntimeWarning: divide by zero encountered in true_divide
  print(array1 / array2)


---

### Comparison Operators

In [64]:
a1 = np.arange(0, 9)
print(a1)
print(a1 == 5)
print(a1 != 5)
print(a1 <= 5)
print(a1 > 5)
print(a1 >= 5)

[0 1 2 3 4 5 6 7 8]
[False False False False False  True False False False]
[ True  True  True  True  True False  True  True  True]
[ True  True  True  True  True  True False False False]
[False False False False False False  True  True  True]
[False False False False False  True  True  True  True]


In [65]:
array1 = np.arange(0, 9).reshape(3,3)
print(array1)

print(np.sum(array1))
print(np.count_nonzero(array1 > 5))
print(np.sum(array1 > 5))
print(np.sum(array1 > 5, axis=0))
print(np.sum(array1 > 5, axis=1))


print(np.any(array1 > 5))
print(np.any(array1 > 5, axis=0))
print(np.any(array1 > 5, axis=1))

print(np.all(array1 > 5))
print(np.all(array1 > 5, axis=0))
print(np.all(array1 > 5, axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
36
3
3
[1 1 1]
[0 0 3]
True
[ True  True  True]
[False False  True]
False
[False False False]
[False False  True]


---
### Broadcasting
https://numpy.org/doc/stable/user/basics.broadcasting.html

In [66]:
array1 = np.array([1,2,3])
array2 = np.array(5)
print(array1 + array2)


[6 7 8]


In [67]:
array1 = [[0,1,2], [3,4,5], [6,7,8]]
array2 = [10,20,30]

array1 = np.array(array1)
array2 = np.array(array2)

print(array1)
print('--------------------------')
print(array2)
print('--------------------------')
print(array1 + array2)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------------------
[10 20 30]
--------------------------
[[10 21 32]
 [13 24 35]
 [16 27 38]]


In [68]:
array1 = [[0,1,2], [3,4,5], [6,7,8]]
print(array1)
print('--------------------------')
array2 = np.array([10,20,30]).reshape((3,1))
print(array2)
print('--------------------------')
print(array1 + array2)

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
--------------------------
[[10]
 [20]
 [30]]
--------------------------
[[10 11 12]
 [23 24 25]
 [36 37 38]]


In [69]:
array = np.random.randint(-5, 10, size=9)
print(array)
print('--------------------------')
print(np.square(array))
print('--------------------------')
print(np.sqrt(array))

[-1  1  2  5  5  4  5  9  4]
--------------------------
[ 1  1  4 25 25 16 25 81 16]
--------------------------
[       nan 1.         1.41421356 2.23606798 2.23606798 2.
 2.23606798 3.         2.        ]


C:\Users\namju\AppData\Local\Temp\ipykernel_9876\192326792.py:6: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(array))


In [70]:
array = np.random.randint(-10, 10, size=9)
print(array)
print('--------------------------')
print(np.absolute(array))

[  1 -10  -2   5   0   5  -6 -10   1]
--------------------------
[ 1 10  2  5  0  5  6 10  1]


In [71]:
array = np.random.randint(-10, 10, size=9)
print(array)
print('--------------------------')
print(np.power(array, 2))
print('--------------------------')
print(np.exp(array))
print(np.exp2(array))
print('--------------------------')
print(np.log(array))
print(np.log2(array))
print(np.log10(array))

[-2 -3 -2  2  6 -4 -2  0 -9]
--------------------------
[ 4  9  4  4 36 16  4  0 81]
--------------------------
[1.35335283e-01 4.97870684e-02 1.35335283e-01 7.38905610e+00
 4.03428793e+02 1.83156389e-02 1.35335283e-01 1.00000000e+00
 1.23409804e-04]
[2.500000e-01 1.250000e-01 2.500000e-01 4.000000e+00 6.400000e+01
 6.250000e-02 2.500000e-01 1.000000e+00 1.953125e-03]
--------------------------
[       nan        nan        nan 0.69314718 1.79175947        nan
        nan       -inf        nan]
[      nan       nan       nan 1.        2.5849625       nan       nan
      -inf       nan]
[       nan        nan        nan 0.30103    0.77815125        nan
        nan       -inf        nan]


C:\Users\namju\AppData\Local\Temp\ipykernel_9876\961468019.py:9: RuntimeWarning: divide by zero encountered in log
  print(np.log(array))
C:\Users\namju\AppData\Local\Temp\ipykernel_9876\961468019.py:9: RuntimeWarning: invalid value encountered in log
  print(np.log(array))
C:\Users\namju\AppData\Local\Temp\ipykernel_9876\961468019.py:10: RuntimeWarning: divide by zero encountered in log2
  print(np.log2(array))
C:\Users\namju\AppData\Local\Temp\ipykernel_9876\961468019.py:10: RuntimeWarning: invalid value encountered in log2
  print(np.log2(array))
C:\Users\namju\AppData\Local\Temp\ipykernel_9876\961468019.py:11: RuntimeWarning: divide by zero encountered in log10
  print(np.log10(array))
C:\Users\namju\AppData\Local\Temp\ipykernel_9876\961468019.py:11: RuntimeWarning: invalid value encountered in log10
  print(np.log10(array))


In [72]:
### Trigonometrical Function

array = np.linspace(0, np.pi * 2, 6)
print(array)
print('--------------------------')
print(np.sin(array))
print('--------------------------')
print(np.cos(array))
print('--------------------------')
print(np.tan(array))
print('--------------------------')
print(np.arcsin(array))
print('--------------------------')
print(np.arccos(array))
print('--------------------------')
print(np.arctan(array))

[0.         1.25663706 2.51327412 3.76991118 5.02654825 6.28318531]
--------------------------
[ 0.00000000e+00  9.51056516e-01  5.87785252e-01 -5.87785252e-01
 -9.51056516e-01 -2.44929360e-16]
--------------------------
[ 1.          0.30901699 -0.80901699 -0.80901699  0.30901699  1.        ]
--------------------------
[ 0.00000000e+00  3.07768354e+00 -7.26542528e-01  7.26542528e-01
 -3.07768354e+00 -2.44929360e-16]
--------------------------
[ 0. nan nan nan nan nan]
--------------------------
[1.57079633        nan        nan        nan        nan        nan]
--------------------------
[0.         0.89863709 1.19211252 1.31150932 1.37441667 1.41296514]


C:\Users\namju\AppData\Local\Temp\ipykernel_9876\3501248208.py:12: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(array))
C:\Users\namju\AppData\Local\Temp\ipykernel_9876\3501248208.py:14: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(array))


In [73]:
#### sum

array = np.random.randint(0, 9, size=(3,3))
print(array)
print('--------------------------')
print(array.sum(), np.sum(array))
print(array.sum(axis=0), np.sum(array, axis=0))
print(array.sum(axis=1), np.sum(array, axis=1))

[[1 3 2]
 [7 4 1]
 [7 0 5]]
--------------------------
30 30
[15  7  8] [15  7  8]
[ 6 12 12] [ 6 12 12]


In [74]:
#### cumsum https://www.geeksforgeeks.org/numpy-cumsum-in-python/

array = np.array([[0,1,2], [3,4,5], [6,7,8]])
print(array)
print('--------------------------')
print(np.cumsum(array))
print('--------------------------')
print(np.cumsum(array, axis=0))
print('--------------------------')
print(np.cumsum(array, axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------------------
[ 0  1  3  6 10 15 21 28 36]
--------------------------
[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]
--------------------------
[[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]]


In [75]:
# diff

array = np.array([[0,1,2], [3,4,5], [6,7,8]])
print(array)
print('--------------------------')

print(np.diff(array))
print('--------------------------')
print(np.diff(array, axis=0))
print('--------------------------')
print(np.diff(array, axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------------------
[[1 1]
 [1 1]
 [1 1]]
--------------------------
[[3 3 3]
 [3 3 3]]
--------------------------
[[1 1]
 [1 1]
 [1 1]]


In [76]:
# prod

array = np.array([[0,1,2], [3,4,5], [6,7,8]])
print(array)
print('--------------------------')

print(np.prod(array))
print('--------------------------')
print(np.prod(array, axis=0)) 
print('--------------------------')
print(np.prod(array, axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------------------
0
--------------------------
[ 0 28 80]
--------------------------
[  0  60 336]


In [77]:
# cumprod

array = np.array([[0,1,2], [3,4,5], [6,7,8]])
print(array)
print('--------------------------')

print(np.cumprod(array))
print('--------------------------')
print(np.cumprod(array, axis=0))
print('--------------------------')
print(np.cumprod(array, axis=1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------------------
[0 0 0 0 0 0 0 0 0]
--------------------------
[[ 0  1  2]
 [ 0  4 10]
 [ 0 28 80]]
--------------------------
[[  0   0   0]
 [  3  12  60]
 [  6  42 336]]


In [78]:
# dot / matmul

array1 = np.array([[0,1,2], [3,4,5], [6,7,8]])
print(array1)
print('--------------------------')

array2 = np.ones_like(array1)
print(array2)
print('--------------------------')

print(np.dot(array1, array2))
print('--------------------------')
print(np.matmul(array1, array2))


[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------------------
[[1 1 1]
 [1 1 1]
 [1 1 1]]
--------------------------
[[ 3  3  3]
 [12 12 12]
 [21 21 21]]
--------------------------
[[ 3  3  3]
 [12 12 12]
 [21 21 21]]


In [79]:
# cross

x = [1,0,0] # X axis
y = [0,1,0] # Y axis

print(np.cross(x, y)) # Z axis

[0 0 1]


In [80]:
# mean

array = np.array([[0,1,2], [3,4,5], [6,7,8]])
print(array)
print('--------------------------')

print(np.mean(array))
print('--------------------------')
print(np.mean(array, axis = 0 ))
print('--------------------------')
print(np.mean(array, axis = 1 ))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------------------
4.0
--------------------------
[3. 4. 5.]
--------------------------
[1. 4. 7.]


In [81]:
# std

array = np.array([[0,1,2], [3,4,5], [6,7,8]])
print(array)
print('--------------------------')

print(np.std(array))
print('--------------------------')
print(np.std(array, axis = 0 ))
print('--------------------------')
print(np.std(array, axis = 1 ))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------------------
2.581988897471611
--------------------------
[2.44948974 2.44948974 2.44948974]
--------------------------
[0.81649658 0.81649658 0.81649658]


In [82]:
# var

array = np.array([[0,1,2], [3,4,5], [6,7,8]])
print(array)
print('--------------------------')

print(np.var(array))
print('--------------------------')
print(np.var(array, axis = 0 ))
print('--------------------------')
print(np.var(array, axis = 1 ))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------------------
6.666666666666667
--------------------------
[6. 6. 6.]
--------------------------
[0.66666667 0.66666667 0.66666667]


In [83]:
# min

array = np.random.randint(0, 10, (3,3))
print(array)
print('--------------------------')

print(np.min(array))
print('--------------------------')
print(np.min(array, axis = 0 ))
print('--------------------------')
print(np.min(array, axis = 1 ))

[[1 4 7]
 [7 1 1]
 [3 2 9]]
--------------------------
1
--------------------------
[1 1 1]
--------------------------
[1 1 2]


#### max(): 최대값

In [84]:
# max

array = np.random.randint(0, 10, (3,3))
print(array)
print('--------------------------')

print(np.max(array))
print('--------------------------')
print(np.max(array, axis = 0 ))
print('--------------------------')
print(np.max(array, axis = 1 ))

[[8 6 5]
 [3 5 8]
 [5 7 6]]
--------------------------
8
--------------------------
[8 7 8]
--------------------------
[8 8 7]


In [85]:
# argmin

array = np.random.randint(0, 10, (3,3))
print(array)
print('--------------------------')

print(np.argmin(array))
print(np.argmin(array, axis = 0 ))
print(np.argmin(array, axis = 1 ))

[[1 3 2]
 [2 4 2]
 [8 6 1]]
--------------------------
0
[0 0 2]
[0 0 2]


#### argmax(): 최대값 인덱스

In [86]:
# argmax

array = np.random.randint(0, 10, (3,3))
print(array)
print('--------------------------')

print(np.argmax(array))
print('--------------------------')
print(np.argmax(array, axis = 0 ))
print('--------------------------')
print(np.argmax(array, axis = 1 ))

[[2 2 7]
 [4 3 0]
 [5 5 7]]
--------------------------
2
--------------------------
[2 2 0]
--------------------------
[2 0 2]


In [87]:
#### median()

array = np.array([[0,1,2], [3,4,5], [6,7,8]])
print(array)
print('--------------------------')

print(np.median(array))
print('--------------------------')
print(np.median(array, axis = 0 ))
print('--------------------------')
print(np.median(array, axis = 1 ))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
--------------------------
4.0
--------------------------
[3. 4. 5.]
--------------------------
[1. 4. 7.]


In [88]:
#### percentile()

array = np.array([0, 1, 2, 3])
print(array)
print('--------------------------')

print(np.percentile(array, [0, 20, 40, 60, 80, 100], interpolation='linear'))
print('--------------------------')
print(np.percentile(array, [0, 20, 40, 60, 80, 100], interpolation='higher'))
print('--------------------------')
print(np.percentile(array, [0, 20, 40, 60, 80, 100], interpolation='lower'))
print('--------------------------')
print(np.percentile(array, [0, 20, 40, 60, 80, 100], interpolation='nearest'))
print('--------------------------')
print(np.percentile(array, [0, 20, 40, 60, 80, 100], interpolation='midpoint'))

[0 1 2 3]
--------------------------
[0.  0.6 1.2 1.8 2.4 3. ]
--------------------------
[0 1 2 2 3 3]
--------------------------
[0 0 1 1 2 3]
--------------------------
[0 1 1 2 2 3]
--------------------------
[0.  0.5 1.5 1.5 2.5 3. ]


---

Reference: 

https://www.w3schools.com/python/numpy/default.asp

https://www.kaggle.com/code/orhansertkaya/numpy-tutorial-for-beginners

https://www.kaggle.com/code/lavanyashukla01/pandas-numpy-python-cheatsheet

